### ISSUE TITLE
Ability to disable/enable DLS (Dead-letter-station) per station

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#241] opened 2022-07-19 11:29 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
At the moment, the DLS feature is enabled by default for every station and cannot be disabled.
We want to add the ability to enable/disable DLS in a certain station.

**Comment by chirag0002** [comment] 2022-12-29 13:01
Hey @idanasulinmemphis, I want to work on this, also I am very new to the project can you please drop me a few resources from where I can learn and contribute?

- I have joined the discord community to get more involved.

**Comment by idanasulinmemphis** [comment] 2023-01-01 08:35
Hi @chirag0002, glad to have you on board. As you can see the issue is already tagged as "in progress" and will be released in the coming version of Memphis (0.4.3).
What do you think of taking this one?
https://github.com/memphisdev/memphis-broker/issues/579

**Comment by chirag0002** [comment] 2023-01-07 20:31
Hey @idanasulinmemphis, actually I'm very new to this project. So, don't know exactly what to do...if you can provide me with some resources, it would be a great help to me to understand it better.
I'll be very excited to work on the above-mentioned issue.

**Closed** 2023-01-08 12:47 UTC
Labels: Feature Request, good first issue, In Progress
